modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="eco" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ecospherical Expansion" #mandatory
logoFile="examplemod.png" #optional
credits="Apothic0n" #optional
authors="Apothic0n" #optional
description='''
Ecospherical Expansion:

Expanding the ecosphere!
'''